site_name: zju-robotics
site_url: https://bclz19.github.io/zju-robotics/
site_author: bclz19
theme:
  name: material #主题
  palette:
    primary: yellow #顶部颜色

  palette: 

    # Palette toggle for light mode
    - scheme: slate
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
      - navigation.instant   #- header.autohide  #自动隐藏
      #- announce.dismiss   #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
      - navigation.tracking   #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
      - navigation.tabs   #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
      #- navigation.tabs.sticky    #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
      #- navigation.sections   #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
      - navigation.top   # 返回顶部的按钮 在上滑时出现
      - search.suggest   # 搜索输入一些字母时推荐补全整个单词
      - search.highlight   # 搜索出的文章关键词加入高亮
      - navigation.expand   # 打开Tab时左侧目录全部展开
      #- navigation.indexes   #启用节索引页后，可以将文档直接附加到节
      - search.share   #搜索分享按钮
      - content.tabs.link
  markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
    
nav:
  - 首页: 
    - 热烈欢迎24级新同学: index.md
    - 一点严肃的事情: seriousthing.md
  - 所以什么是机器人工程:
    - 所以什么是机器人工程: about_robotics.md
  - 选课指导:
    - 培养方案: select_course/Academic_Program/Academic_Program.md
    - 通识课程: select_course/General/general_index.md
    - 数理基础课: 
      - select_course/math_phy/index.md
      - 线性代数 (甲): select_course/math_phy/linear_algebra/index.md
      - 微积分（甲）Ⅰ: select_course/math_phy/calculus1/index.md
      - 微积分（甲）Ⅱ: select_course/math_phy/calculus2/index.md
      - 大学物理 （甲）Ⅰ: select_course/math_phy/physics1/index.md
      - 大学物理实验: select_course/math_phy/physics_experiment/index.md
      - 大学物理 （甲）Ⅱ: select_course/math_phy/physics2/index.md
      - 测试版面: select_course/math_phy/text.md

    - 思政课: select_course/political/political_index.md
  - 疯狂的机器人:
    - 疯狂的机器人: "crazy_robotics.md"
  - 学长说:
    - senior_speech/index.md
  - 畅所欲言:
    - 畅所欲言: "chats.md"
  - 联系我们: connect_us.md
  - 卷尾语：
