site_name: zju-robotics
site_url: https://zju-robotics.cn/
site_author: bclz19

repo_name: zju-robotics
repo_url: https://github.com/bclz19/zju-robotics/

# theme:
#   name: material #主题
#   language: zh
#   logo: img/favicon.ico
#   features:
#   - content.tabs.link
#   - navigation.instant
#   - navigation.tabs
#   - navigation.tracking
#   - navigation.path
#   - toc.integrate
#   - toc.follow
#   - navigation.top
#   - navigation.footer
#   - navigation.expand
#   - search.highlight
#   - search.share
#   - search.suggest
#   palette: 

#     # Palette toggle for light mode
#     - scheme: slate
#       toggle:
#         icon: material/brightness-7 
#         name: Switch to dark mode

#     # Palette toggle for dark mode
#     - scheme: default
#       toggle:
#         icon: material/brightness-4
#         name: Switch to light mode



#   markdown_extensions:
#   - pymdownx.superfences
#   - pymdownx.tabbed:
#       alternate_style: true


theme:
  name: material
  custom_dir: overrides
  language: zh
  logo: img/favicon.ico
  features:
  # - content.tabs.link
  - navigation.instant
  - navigation.tabs
  - navigation.tracking
  - navigation.path
  - toc.integrate
  - toc.follow
  - navigation.top
  - navigation.footer
  # - navigation.expand

  - search.highlight
  - search.share
  - search.suggest
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # palette: 

  #   # Palette toggle for light mode
  #   - scheme: slate
  #     toggle:
  #       icon: material/brightness-7 
  #       name: Switch to dark mode

  #   # Palette toggle for dark mode
  #   - scheme: default
  #     toggle:
  #       icon: material/brightness-4
  #       name: Switch to light mode
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - docs/js/flower.js

extra_css:
  - docs/css/custom.css
  
nav:
  - 首页: 
    - 热烈欢迎24级新同学: index.md
    - 一点严肃的事情: seriousthing.md
  # - 所以什么是机器人工程:
  #   - 所以什么是机器人工程: about_robotics.md
  - 选课指导:
    - select_course/index.md
    - 培养方案: select_course/Academic_Program/Academic_Program.md
    # - 通识课程: select_course/General/general_index.md
    - 数理基础课: 
      - select_course/math_phy/index.md
      - 线性代数 (甲): select_course/math_phy/linear_algebra/index.md
      - 微积分（甲）Ⅰ: select_course/math_phy/calculus1/index.md
      - 微积分（甲）Ⅱ: select_course/math_phy/calculus2/index.md
      - 大学物理 （甲）Ⅰ: select_course/math_phy/physics1/index.md
      - 大学物理实验: select_course/math_phy/physics_experiment/index.md
      - 大学物理 （甲）Ⅱ: select_course/math_phy/physics2/index.md
      - 程序设计基础与实验: select_course/math_phy/C_language/index.md
      - 测试版面: select_course/math_phy/text.md

    - 思政课: 
      - select_course/political/index.md
      - 形势与政策 Ⅰ: select_course/political/situation_policy1/index.md
      - 思想道德与法治: select_course/political/morality_law/index.md
      - 中国近现代史纲要: select_course/political/modern_history/index.md
      - 马克思主义基本原理: select_course/political/marxism_basic/index.md
      - 毛泽东思想和中国特色社会主义理论体系概论: select_course/political/mao_thought/index.md
      - 习近平新时代中国特色社会主义思想概论: select_course/political/xi_thought/index.md
      - 形势与政策 Ⅱ: select_course/political/situation_policy2/index.md
      - 军事理论: select_course/political/military_theory/index.md

    - 专业基础课: 
      - select_course/major_basic/index.md
      - 工程图学: select_course/major_basic/engineering_drawing/index.md
      - 常微分方程: select_course/major_basic/ode/index.md
      - 复变函数与积分变换: select_course/major_basic/Complex_Variable_Functions&Integral_Transformation/index.md
      - 理论力学（乙）: select_course/major_basic/Theoretical_Mechanics/index.md
      - 电路与模拟电子技术: select_course/major_basic/Electric_Circuit_and_Analog_Electronic_Technology/index.md
      - 电路与模拟电子技术实验: select_course/major_basic/Electric_Circuit_and_Analog_Electronic_Technology_Experiment/index.md
      - 概率论与数理统计: select_course/major_basic/Probability_and_Statistics/index.md
    
    - 专业必修课: 
      - select_course/major_mandatory/index.md
      - 机器人与人工智能导论: select_course/major_mandatory/Introduction_To_Robotics_And_Artificial_Intelligence/index.md
      - 嵌入式系统: select_course/major_mandatory/Embedded_System/index.md
      - 自动控制理论（乙）: select_course/major_mandatory/Principle_Of_Automatic_Control/index.md
      - 机械设计基础（甲）: select_course/major_mandatory/Fundamentals_of_Mechanical_Design/index.md
      - 机器人学Ⅰ: select_course/major_mandatory/robotics1/index.md
      - 机器人学Ⅱ: select_course/major_mandatory/robotics2/index.md
      - 机器人传感技术: select_course/major_mandatory/Robot_Sensingtechnology/index.md
      - 机器视觉: select_course/major_mandatory/Machine_Vision/index.md
      - 人工智能与机器学习: select_course/major_mandatory/Artificial_Intelligence_And_Machine_Learning/index.md

    - 短学期课程:
      - select_course/short_term/index.md
      - ROS与机器人仿真软件: select_course/short_term/ros/index.md
      - 专业认知: select_course/short_term/Major_Cognition/index.md
      - 机器人基础实践: select_course/short_term/Basic_Practice_Of_Robot/index.md
      
    # - 疯狂的机器人:
  
    #   - 疯狂的机器人: "crazy_robotics.md"
  - 学长说:
    - senior_speech/index.md
    - 所以机器人工程到底是什么: senior_speech/whats_robotics.md
    - 科研方向/所需基础: senior_speech/research_guidance.md
    - 数学/计算机（等待命名）: 
      - senior_speech/math&computer_guidance.md
      - 线性代数概论: senior_speech/introduction_to_LinearAlgebra.html
  
  - 消失的学期:
    - 实用技能: missing_semester/index.md
  - 畅所欲言: comment.md
  - 联系我们: connect_us.md
  - 卷尾语: end.md
